
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo-App',
  description: 'Generated by create next app',
};

const queryClient = new QueryClient();

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <SessionProvider>
          <QueryClientProvider client={queryClient}>
              {children}
          </QueryClientProvider>
      </SessionProvider>
      </body>
      </html>
  );
}
